#### How Dropout Works

A regularization technique for NN. Zeroes out neurons randomly in NN (Prevents units from co-adapting too strongly), Applied during training only. So, every neuron is weighted sum of inputs, followed by activation. 

If we assume every weight to be 1 and input to be 1 as well , then a neuron input would 1.1 + 1.1 + 1.1 + .... 100 times = 100

If we had during training 40% dropout rate, so roughly 40% of neurons would be 0, Hence the updated input to neuron in following layer would be just 60, Hence during training it is 60 while for inference it would be 100.

For an activation vector 

```
x, x = x * m (where m is sampling a mask from Bernoulli m_i ~ Bernoulli (1 - p)), scale by 1/ (1 - p) inverted dropout = x  = x / (1 - p)
```
Hence dropout effects the scale of activation, and to ensure model remain consistent. Droput also scales all activation during training by a factor of 1 / (1 - p), Hence if p = 40 %  i.e 0.4 then 60. (1/ (1-0.4)) = 100. Hence making training & inference consistent


##### Why dropout helps :

It acts an implicit ensemble of many subnetworks. each training pass uses a different random subnetwork and this reduces overfitting by avoiding reliance on any single feature path, hence improving generalization on smaller datasets

Common dropout rates:

0.1 to 0.3 for large models
0.4 to 0.5 for smaller fully connected nets
too high p can underfit




In [9]:
import torch
import torch.nn as nn

dropout_layer = nn.Dropout(0.2)
p = 0.2
x = torch.randn((1, 5))

print(x)
print(x/(1-p)) # same as dropout
print(dropout_layer(x)) # droput layer

# Doing the same thing in evaluation mode neither drops nor scales as expected:
dropout_layer.eval()
print(dropout_layer(x))

tensor([[ 0.3227,  0.1190,  0.2705,  0.0850, -0.1035]])
tensor([[ 0.4034,  0.1488,  0.3381,  0.1063, -0.1294]])
tensor([[ 0.4034,  0.1488,  0.3381,  0.1063, -0.1294]])
tensor([[ 0.3227,  0.1190,  0.2705,  0.0850, -0.1035]])
