In [1]:
## BROADCASTING
# 1. 2 array with different shape, numpy will strecth the smaller array
# along the axis with size 1 so the shapes matches element wise.

import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]]) # Shape (2, 3)
b = np.array([[10], [20]]) # Shape (2, 1)

# b is broadcast to shape (2, 3) along the axis 1:
# [[10, 10, 10],
#   [20, 20, 20] ]

result = a + b
print(result)


[[11 12 13]
 [24 25 26]]


In [6]:
## SQUEEZE
# 1. removes axes of length 1 from an array's shape
# 2. sometimes after operations like keepdims=True,extra dim of size 1,(1 3)
# 3. removes axes of length 1
arr = np.array([1, 2, 3]) # Shape (1, 3)
print(arr.shape)

arr = arr.reshape(1, -1)
print(arr.shape)
print(arr)

arr_squeezed = arr.squeeze()
print(arr_squeezed.shape) # Shape (3,)
print(arr_squeezed)


(3,)
(1, 3)
[[1 2 3]]
(3,)
[1 2 3]
