#### Vectors in Python

In [2]:
# Vectors as tuples of number like (-1.2, 3.5, 4.5)
# Matrices as table of scalars

x = (1, 2, 3)
type(x)

# We can perform vector operations with tuples.
x = (1, 2, 3)
y = (4, 5, 6)

x + y # The result is concatenation of x and y.

# Same thing happens with list
x = [1, 2, 3]
y = [4, 5, 6]

x + y

[1, 2, 3, 4, 5, 6]

In [3]:
# Methods are functions attached to the class.
# First method is __init__, runs when an object of class is instantiated
# Methods prefix and suffix with dnders are called magic methods
class Vector:
    def __init__(self, coords): # coords attached to attribute coords
        self.coords = coords # self is concrete object that is being init
    
    # string representation to vector class by implementing method
    def __repr__(self):
        return str(self.coords)
    
    # earlier setting & accessing coords requires accessing it, not a good practice, as it is internal to object
    def __getitem__(self, idx):
        return self.coords[idx]
    
    def __setitem__(self, idx, value):
        self.coords[idx] = value

x = Vector([1, 2, 3])
print(x) # class and the memory address of object x

print(x.coords) # attribute can be accesss with synatx of obj_name.

print(x[0])
x[0] = 42
print(x)

[1, 2, 3]
[1, 2, 3]
1
[42, 2, 3]


In [4]:
# Python a + b is equivalent to calling __add__ method
[1, 2].__add__([3, 4])

[1, 2, 3, 4]

In [5]:
class Vector(Vector):
    def __add__(self, other):
        return Vector(coords=[
            x + y for x, y in zip(self.coords, other.coords)
        ])
    
    def __mul__(self, other):
        return Vector([other * x for x in self.coords])
    
    def __rmul__(self, other):
        return Vector(coords=[other * x for x in self.coords])
    
x = Vector([1, 2, 3])
y = Vector([4, 5, 6])

print(x + y)
# becomes a method call, x is a vectod and looks for its __add__ method.
# translates expression to x.__add__(y)
# self is assigbed object on left x, and other to object on right y

x = Vector([1, 2, 3])
print(x * 2.0)

2.0 * x
# it is 2.0__mul__(x), __mul__ of float does not support vector arguments
# we implemt rmul method, multiplications from right.
print(2.0 * x)

[5, 7, 9]
[2.0, 4.0, 6.0]
[2.0, 4.0, 6.0]


#### Vectors in Numpy

In [6]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x, y, x + y, 2.0 * x)
print(x * y) # performs element wise product operation.

def dot(x, y):
    return sum([xi * yi for xi, yi in zip(x, y)])

# Also implemented in numpy
np.dot(x, y)

[1 2 3] [4 5 6] [5 7 9] [2. 4. 6.]
[ 4 10 18]


32

#### Matrices

In [24]:
from sklearn.datasets import fetch_california_housing

housing_data = fetch_california_housing()
X, y = housing_data["data"], housing_data["target"]

X[:5]

array([[ 8.32520000e+00,  4.10000000e+01,  6.98412698e+00,
         1.02380952e+00,  3.22000000e+02,  2.55555556e+00,
         3.78800000e+01, -1.22230000e+02],
       [ 8.30140000e+00,  2.10000000e+01,  6.23813708e+00,
         9.71880492e-01,  2.40100000e+03,  2.10984183e+00,
         3.78600000e+01, -1.22220000e+02],
       [ 7.25740000e+00,  5.20000000e+01,  8.28813559e+00,
         1.07344633e+00,  4.96000000e+02,  2.80225989e+00,
         3.78500000e+01, -1.22240000e+02],
       [ 5.64310000e+00,  5.20000000e+01,  5.81735160e+00,
         1.07305936e+00,  5.58000000e+02,  2.54794521e+00,
         3.78500000e+01, -1.22250000e+02],
       [ 3.84620000e+00,  5.20000000e+01,  6.28185328e+00,
         1.08108108e+00,  5.65000000e+02,  2.18146718e+00,
         3.78500000e+01, -1.22250000e+02]])

In [30]:
class Matrix:
    def __init__(self, rows):
        self.rows = rows
        self.shape = (len(self.rows), len(self.rows[0]))

    def __repr__(self):
        if not self.rows:
            return "[]"
        if not self.rows[0]:
            return "[[]]"
        
        col_widths = [max(len(str(item)) for item in col)
                      for col in zip(*self.rows)]
        
        row_strings = [
            f"[{' '.join(str(item).rjust(col_widths[i])
                         for i, item in enumerate(row))}]"
            for row in self.rows
        ]

        return '\n'.join(row_strings)
    
    def __getitem__(self, idx):
        i, j = idx[0], idx[1]
        return self.rows[i][j]
    
    def __setitem__(self, idx, value):
        i, j = idx[0], idx[1]
        self.rows[i][j] = value

X = Matrix([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
            [10, 11, 12]])

print(X)
print(X[0, 0])
X[0, 0] = 42
print(X)

[ 1  2  3]
[ 4  5  6]
[ 7  8  9]
[10 11 12]
1
[42  2  3]
[ 4  5  6]
[ 7  8  9]
[10 11 12]


In [1]:
class Matrix(Matrix):
    def __add__(self, other):
        return Matrix([
            [x + y for x, y in zip(xs, ys)]
            for xs, ys in zip(self.rows, other.rows)
        ])
    
    def __mul__(self, other):
        return Matrix([
            [other * x for x in xs]
            for xs in self.rows
        ])
    
    def __rmul__(self, other):
        return self * other
    

X = Matrix([[1, 2, 3],
            [4, 5, 6]])
Y = Matrix([[7, 8, 9],
            [10, 11, 12]])

print(X + Y)
print(2.0 * X)
print (X * 2.0)

NameError: name 'Matrix' is not defined